---
title: "Classifying Asteroids from closest to furthest using orbital parameters"
#subtitle: ""
author: Sitong Zhang, Tonylouis Fondzenyuy, Zhekai Chen
institute: "University of Edinburgh"
date: "`r Sys.Date()`"
---
## Introduction

In this data science project (which can be found at: https://github.com/Fondzenyuy/IDS_project.git), the issue we are discussing is the classification of asteroids based on their closeness to the Earth. We want to do the calculation in two different ways using two distance dependent orbital variables . The first main variable is use the Semi major axis, and for the second is the orbital period. 

One of our team members studies physics, and he suggested the source website which was used to extract the required data for our project. The website is obtained from the small-body data archive of the National Aeronautics and Space Association (NASA).

Just like the pictures of the data table shown in our presentation slides, our data extraction from the NASA archive has key steps. We need to choose different categories in these four parts which can make us get the more relevant data as we want. For the first part which is to limit by object kind, we need to choose the asteroids (our object of interest for the project). After that we need to choose the asteroid orbit classes and choose the asteroid range we want to get (asteroids within the solar system).

For the fourth part which is most important ,we need to choose the variables we want to get. In this step, we chosed thirteen different variables ; neo,diameter e ,a ,q, I ,om ,w, pery ,moid, sigamw, dates of first and last observations.
These different variables have different meanings. For the `neo`, it stands for near earth object, a collective term for asteroids whose orbits are very close to earth's. The distance difference between orbits of near earth objects and the earth are typically smaller than 1.3 astronomical units. In addition, if an neo has a similar size with the earth, it becomes a potentially hazardous object (pho as shown on the data archive). The variable `e` is the eccentricity of the object.This is a constant that describes how much an asteroid's orbit deviate from the roughly circular orbit of the earth around the sun. The parameter `a` is the semi major axis, the length of an imaginary line between the sun and the asteroid as it covers an elliptical path around the sun (according to Kepler's first law of planetary motion). The q is perihelion distance, that is the closest possible distance between earth and asteroid. `i` is the inclination, `om` is the longitude of the ascending node, the angular pitch between the asteroid at the Ascending node and the asteroid at the point when the ecliptic plane and equatorial plane meet. `w` is the argument of perihelion which is the angle of the orbit from the ascending node to perihelion. `per_y` is the time period per years which is a suitable time unit for measuring periods of astronomical bodies. `Moid` is the smallest distance between two orbits while q which is the smallest distance between two objects.
 

## Method
For exploring whether the semi-long axis and orbital period have the same effect on the ordering of asteroid distances, we have two ways to approach the problem.

 

In method one, we use a ggplot plot to make the data more visual, allowing us to look at it more intuitively. We create two plots based on different variables in the table: Making a histogram with the x-axis as `a` (semi-long axis) and the y-axis as the number of asteroids that occupy a certain semi-long interval. Similarly, we make another histogram with the x-axis as `per_y` (orbital period) and the y-axis as the number of asteroids occupied in each orbital period interval. 

 

We do this because if the semi-long axis and the orbital period have the same effect on the asteroid ordering, their visualizations show a similar trend (since each intervals corresponding to the two visualizations will have almost the same number of asteroids); if the effects are different, it means that the two variables do not have the same effect on the asteroid ordering.

Here is the code for these histograms:

`asteroid %>%`

  `ggplot(aes(x = a)) +`
  `geom_histogram(aes(y = ..count..), binwidth = 0.005) + xlim(c(0,6)) +`
  
  `labs(x = "semi-major axis (a) in AU")`
  
  
  `asteroid %>%`
  
  `ggplot(aes(x = asteroid$per_y)) +`
  
  `geom_histogram(aes(y = ..count..), binwidth = 0.005) + xlim(c(0,6)) +`
  
  `labs(x = "orbital period (per_y)")`

In method two, we will explore whether there is a linear relationship between the variable a and the variable `per_y`. So, we will create a linear model between `a` and `per_y` (set_engine("lm")), and in this model, `a` is the response variable, `per_y` is the explanatory variable. Then we apply the `tidy` function for this model, in which we find the R-squared value. 

 

Due to the similar order of magnitude of the values of `a` and `per_y`, we can investigate the relationship between these variables using the linear model method.

Here is the code used for the linear model:

`model1 <- lm(a~per_y, data = asteroid)`

`summary(model1)`

 

`a_pery_fit <- linear_reg() %>%`

  `set_engine("lm") %>%`
  
  `fit(a~per_y, data = asteroid) %>%`
  
  `tidy()`


## Discussion of Results & Conclusion
### Discussion of Results

The histograms above show the distribution of the asteroids using the semi-major axis and orbital periods. These histograms also contain information on the closeness (classification by distance) of these asteroids to us since the orbital parameters used are distance-dependent.
As seen on the plots, both classifications show an identical pattern across the entire asteroid data set. This can be explained mathematically by the equation of Kepler's third law of planetary motion :

\begin{equation}
T^{2} = a^{3}
\end{equation}

whereby T denotes the orbital period (``per_y`) in years and a denotes the distance between the earth and any given object in the solar system.


Kepler's shows a direct linear relationship between the semi-major axis and the orbital period which vindicates the identical pattern in the histograms obtained by ranking asteroids by selected variables. 

The histogram consists of spacings between the histogram bins of the asteroid positions. These spacings physically represent the Kirkwood gaps in our solar system. As the name implies, Kirkwood gaps refer to the gaps or dips in the distribution of the semi-major axes (or equivalently of the orbital periods) of the orbits of asteroids. Due to the relatively small mass of the asteroids when compared to the planets in our solar system, the asteroids tend to be affected by the resonances (gravitational effects) of Jupiter and the other icy giants namely (in descending order of proximity to the earth): Saturn, Uranus, Neptune and Pluto. The gravitational resonances of the listed planets clears a region around themselves which cannot be occupied by asteroids. As a result, the first dip on the plotted histograms (from the left) coincides with the region between Mars and Jupiter . This first gap is commonly referred to as the asteroid belt. The next 4 dips represent the regions cleared by the gravitational effects of the icy giants in descending order from the sun as earlier mentioned.

As shown on both histograms, the earliest asteroids can be found around 2AU (2 Astronomical units) whereby 1AU denotes the distance between the earth and the sun. Hence, the closest asteroids to us in the solar system can be found at a distance which is at least twice the sun-earth distance. 
Models
We can model the relationship between the semi-major axes and orbital periods across our classification data set. The values of these parameters are numeric thereby permitting the use of a linear regression model. As described in the methods section, the `tidymodels` package was used to compute the regression model. 

The goodness of fit of our model (R-squared) gave us a value of 0.9979. Since the R-squared value is very close to 1, it confirms the direct correlation between orbital semi-major axis and period as equivalent parameters for classifying asteroids. Interestingly, when two other distant-dependent orbital parameters, orbital inclination (i) and eccentricity (e) are used as additional predictors to the model, the value of R-squared moves slightly closer to 1. Hence, additional parameters can play a role in helping us get a slightly accurate classification of the asteroids. However, these additional parameters by themselves cannot be primarily used as the only predictors since they give very small contributions to the overall R-squared value.

### Conclusion
To conclude, semi-major axis and orbital periods give the same classification of asteroids in our data set. Lastly, asteroids being solar system bodies (and substantially smaller in size than planets) obey Kepler's laws of motion.

---

